<?php

return [
    // Couleurs
    'color_primary' => 'nullable|string|max:20',
    'color_primary_light' => 'nullable|string|max:20',
    'color_accent' => 'nullable|string|max:20',
    'color_bg' => 'nullable|string|max:20',
    'color_card' => 'nullable|string|max:20',
    'color_border' => 'nullable|string|max:20',
    'color_text' => 'nullable|string|max:20',
    'color_text_secondary' => 'nullable|string|max:20',

    // Global
    'global_font' => 'nullable|string|max:30',
    'global_mc_font_headings' => 'nullable|string|max:2',
    'font_navbar' => 'nullable|string|max:30',
    'font_hero_title' => 'nullable|string|max:30',
    'font_hero_subtitle' => 'nullable|string|max:30',
    'font_headings' => 'nullable|string|max:30',
    'font_footer' => 'nullable|string|max:30',
    'font_stats' => 'nullable|string|max:30',
    'global_border_radius' => 'nullable|string|max:20',
    'global_animations' => 'nullable|string|max:2',
    'global_animation_speed' => 'nullable|string|max:20',
    'global_glow_effects' => 'nullable|string|max:2',
    'global_page_width' => 'nullable|string|max:6',
    'global_loading_bar' => 'nullable|string|max:2',
    'global_scrollbar_style' => 'nullable|string|max:20',
    'global_scroll_animation' => 'nullable|string|max:20',

    // Navbar
    'navbar_style' => 'nullable|string|max:20',
    'navbar_height' => 'nullable|string|max:5',
    'navbar_logo_size' => 'nullable|string|max:5',
    'navbar_show_name' => 'nullable|string|max:2',
    'navbar_sticky' => 'nullable|string|max:2',
    'navbar_shadow' => 'nullable|string|max:2',
    'navbar_border_color' => 'nullable|string|max:20',

    // Hero
    'hero_background' => 'nullable|string|max:500',
    'hero_logo' => 'nullable|string|max:500',
    'hero_title' => 'nullable|string|max:200',
    'hero_subtitle' => 'nullable|string|max:500',
    'hero_particles' => 'nullable|string|max:2',
    'hero_particles_color' => 'nullable|string|max:20',
    'hero_height' => 'nullable|string|max:5',
    'hero_overlay_style' => 'nullable|string|max:20',
    'hero_overlay_opacity' => 'nullable|string|max:5',
    'hero_title_size' => 'nullable|string|max:10',
    'hero_animation' => 'nullable|string|max:20',
    'hero_button_text' => 'nullable|string|max:50',
    'hero_button_url' => 'nullable|string|max:200',
    'hero_button_icon' => 'nullable|string|max:50',
    'hero_button_style' => 'nullable|string|max:20',
    'hero_button2_text' => 'nullable|string|max:50',
    'hero_button2_url' => 'nullable|string|max:200',
    'hero_button2_icon' => 'nullable|string|max:50',
    'hero_button2_style' => 'nullable|string|max:20',
    'server_ip' => 'nullable|string|max:100',
    'hero_copy_ip' => 'nullable|string|max:2',
    'hero_server_card' => 'nullable|string|max:2',
    'hero_server_card_style' => 'nullable|string|max:20',
    'hero_server_card_label' => 'nullable|string|max:50',
    'hero_server_card_online_text' => 'nullable|string|max:50',
    'hero_server_card_copy_ip' => 'nullable|string|max:2',
    'hero_ip_style' => 'nullable|string|max:20',
    'hero_ip_color' => 'nullable|string|max:20',
    'hero_ip_bg_color' => 'nullable|string|max:20',
    'hero_ip_size' => 'nullable|string|max:20',

    // Features
    'features_enabled' => 'nullable|string',
    'features_title' => 'nullable|string|max:200',
    'features_subtitle' => 'nullable|string|max:500',
    'features_columns' => 'nullable|string|max:2',
    'features_card_style' => 'nullable|string|max:20',
    'features_icon_style' => 'nullable|string|max:20',
    'feature_1_icon' => 'nullable|string|max:50',
    'feature_1_title' => 'nullable|string|max:100',
    'feature_1_desc' => 'nullable|string|max:500',
    'feature_2_icon' => 'nullable|string|max:50',
    'feature_2_title' => 'nullable|string|max:100',
    'feature_2_desc' => 'nullable|string|max:500',
    'feature_3_icon' => 'nullable|string|max:50',
    'feature_3_title' => 'nullable|string|max:100',
    'feature_3_desc' => 'nullable|string|max:500',
    'feature_4_icon' => 'nullable|string|max:50',
    'feature_4_title' => 'nullable|string|max:100',
    'feature_4_desc' => 'nullable|string|max:500',
    'feature_5_icon' => 'nullable|string|max:50',
    'feature_5_title' => 'nullable|string|max:100',
    'feature_5_desc' => 'nullable|string|max:500',
    'feature_6_icon' => 'nullable|string|max:50',
    'feature_6_title' => 'nullable|string|max:100',
    'feature_6_desc' => 'nullable|string|max:500',

    // Stats
    'stats_enabled' => 'nullable|string',
    'stats_style' => 'nullable|string|max:20',
    'stat_1_source' => 'nullable|string|max:20',
    'stat_1_icon' => 'nullable|string|max:50',
    'stat_1_value' => 'nullable|string|max:50',
    'stat_1_label' => 'nullable|string|max:100',
    'stat_2_source' => 'nullable|string|max:20',
    'stat_2_icon' => 'nullable|string|max:50',
    'stat_2_value' => 'nullable|string|max:50',
    'stat_2_label' => 'nullable|string|max:100',
    'stat_3_source' => 'nullable|string|max:20',
    'stat_3_icon' => 'nullable|string|max:50',
    'stat_3_value' => 'nullable|string|max:50',
    'stat_3_label' => 'nullable|string|max:100',
    'stat_4_source' => 'nullable|string|max:20',
    'stat_4_icon' => 'nullable|string|max:50',
    'stat_4_value' => 'nullable|string|max:50',
    'stat_4_label' => 'nullable|string|max:100',

    // Staff
    'staff_enabled' => 'nullable|string',
    'staff_title' => 'nullable|string|max:200',
    'staff_subtitle' => 'nullable|string|max:500',
    'staff_columns' => 'nullable|string|max:2',
    'staff_avatar_style' => 'nullable|string|max:20',
    'staff_1_name' => 'nullable|string|max:50',
    'staff_1_role' => 'nullable|string|max:50',
    'staff_1_avatar' => 'nullable|string|max:500',
    'staff_2_name' => 'nullable|string|max:50',
    'staff_2_role' => 'nullable|string|max:50',
    'staff_2_avatar' => 'nullable|string|max:500',
    'staff_3_name' => 'nullable|string|max:50',
    'staff_3_role' => 'nullable|string|max:50',
    'staff_3_avatar' => 'nullable|string|max:500',
    'staff_4_name' => 'nullable|string|max:50',
    'staff_4_role' => 'nullable|string|max:50',
    'staff_4_avatar' => 'nullable|string|max:500',
    'staff_5_name' => 'nullable|string|max:50',
    'staff_5_role' => 'nullable|string|max:50',
    'staff_5_avatar' => 'nullable|string|max:500',
    'staff_6_name' => 'nullable|string|max:50',
    'staff_6_role' => 'nullable|string|max:50',
    'staff_6_avatar' => 'nullable|string|max:500',
    'staff_7_name' => 'nullable|string|max:50',
    'staff_7_role' => 'nullable|string|max:50',
    'staff_7_avatar' => 'nullable|string|max:500',
    'staff_8_name' => 'nullable|string|max:50',
    'staff_8_role' => 'nullable|string|max:50',
    'staff_8_avatar' => 'nullable|string|max:500',
    'staff_9_name' => 'nullable|string|max:50',
    'staff_9_role' => 'nullable|string|max:50',
    'staff_9_avatar' => 'nullable|string|max:500',
    'staff_10_name' => 'nullable|string|max:50',
    'staff_10_role' => 'nullable|string|max:50',
    'staff_10_avatar' => 'nullable|string|max:500',
    'staff_11_name' => 'nullable|string|max:50',
    'staff_11_role' => 'nullable|string|max:50',
    'staff_11_avatar' => 'nullable|string|max:500',
    'staff_12_name' => 'nullable|string|max:50',
    'staff_12_role' => 'nullable|string|max:50',
    'staff_12_avatar' => 'nullable|string|max:500',

    // News
    'news_enabled' => 'nullable|string',
    'news_title' => 'nullable|string|max:200',
    'news_subtitle' => 'nullable|string|max:500',
    'news_count' => 'nullable|string|max:3',
    'news_columns' => 'nullable|string|max:2',
    'news_show_image' => 'nullable|string|max:2',
    'news_show_date' => 'nullable|string|max:2',
    'news_show_excerpt' => 'nullable|string|max:2',
    'news_excerpt_length' => 'nullable|string|max:5',

    // Discord
    'discord_id' => 'nullable|string|max:30',
    'discord_invite_url' => 'nullable|string|max:200',
    'discord_title' => 'nullable|string|max:200',
    'discord_description' => 'nullable|string|max:1000',
    'discord_style' => 'nullable|string|max:20',

    // CTA
    'cta_enabled' => 'nullable|string',
    'cta_background' => 'nullable|string|max:500',
    'cta_title' => 'nullable|string|max:200',
    'cta_subtitle' => 'nullable|string|max:500',
    'cta_button_text' => 'nullable|string|max:50',
    'cta_button_url' => 'nullable|string|max:200',
    'cta_button_icon' => 'nullable|string|max:50',
    'cta_button_style' => 'nullable|string|max:20',

    // Custom code
    'custom_css' => 'nullable|string|max:10000',
    'custom_js' => 'nullable|string|max:10000',
    'custom_head_code' => 'nullable|string|max:5000',

    // Sections order
    'sections_order' => 'nullable|string|max:200',

    // Footer
    'footer_style' => 'nullable|string|max:20',
    'footer_bg_color' => 'nullable|string|max:20',
    'footer_description' => 'nullable|string|max:500',
    'footer_show_logo' => 'nullable|string|max:2',
    'footer_links_new_tab' => 'nullable|string|max:2',
    'footer_columns' => 'nullable|string|max:2',
    'footer_col1_title' => 'nullable|string|max:50',
    'footer_col1_content' => 'nullable|string|max:20',
    'footer_col2_title' => 'nullable|string|max:50',
    'footer_col3_title' => 'nullable|string|max:50',
    'footer_col4_title' => 'nullable|string|max:50',
    'footer_links' => 'nullable|array',
    'footer_legal_link1_text' => 'nullable|string|max:50',
    'footer_legal_link1_url' => 'nullable|string|max:200',
    'footer_legal_link2_text' => 'nullable|string|max:50',
    'footer_legal_link2_url' => 'nullable|string|max:200',
    'footer_legal_link3_text' => 'nullable|string|max:50',
    'footer_legal_link3_url' => 'nullable|string|max:200',
    'footer_legal_link4_text' => 'nullable|string|max:50',
    'footer_legal_link4_url' => 'nullable|string|max:200',
    'footer_legal_link5_text' => 'nullable|string|max:50',
    'footer_legal_link5_url' => 'nullable|string|max:200',
    'footer_legal_link6_text' => 'nullable|string|max:50',
    'footer_legal_link6_url' => 'nullable|string|max:200',
    'footer_col4_link1_text' => 'nullable|string|max:50',
    'footer_col4_link1_url' => 'nullable|string|max:200',
    'footer_col4_link2_text' => 'nullable|string|max:50',
    'footer_col4_link2_url' => 'nullable|string|max:200',
    'footer_col4_link3_text' => 'nullable|string|max:50',
    'footer_col4_link3_url' => 'nullable|string|max:200',
    'footer_col4_link4_text' => 'nullable|string|max:50',
    'footer_col4_link4_url' => 'nullable|string|max:200',
    'footer_col4_link5_text' => 'nullable|string|max:50',
    'footer_col4_link5_url' => 'nullable|string|max:200',
    'footer_col4_link6_text' => 'nullable|string|max:50',
    'footer_col4_link6_url' => 'nullable|string|max:200',
    'footer_custom_html' => 'nullable|string|max:2000',
    'footer_social_discord' => 'nullable|string|max:200',
    'footer_social_twitter' => 'nullable|string|max:200',
    'footer_social_youtube' => 'nullable|string|max:200',
    'footer_social_instagram' => 'nullable|string|max:200',
    'footer_social_tiktok' => 'nullable|string|max:200',
    'footer_social_github' => 'nullable|string|max:200',
    'footer_social_twitch' => 'nullable|string|max:200',
    'footer_social_facebook' => 'nullable|string|max:200',
    'footer_social_telegram' => 'nullable|string|max:200',
    'footer_social_linkedin' => 'nullable|string|max:200',
    'footer_social_snapchat' => 'nullable|string|max:200',
    'footer_social_steam' => 'nullable|string|max:200',
    'footer_social_reddit' => 'nullable|string|max:200',
    'footer_copyright' => 'nullable|string|max:200',

    // Error pages
    'maintenance_custom_message' => 'nullable|string|max:500',
    'error_404_style' => 'nullable|string|max:20',
    'error_404_title' => 'nullable|string|max:100',
    'error_404_subtitle' => 'nullable|string|max:200',
    'error_404_message' => 'nullable|string|max:500',
    'error_404_image' => 'nullable|string|max:500',
    'error_404_bg_image' => 'nullable|string|max:500',
    'error_404_show_search' => 'nullable|string|max:2',
    'error_404_button_text' => 'nullable|string|max:50',
    'error_404_button_icon' => 'nullable|string|max:50',
    'error_404_button_style' => 'nullable|string|max:20',
    'error_404_button2_text' => 'nullable|string|max:50',
    'error_404_button2_url' => 'nullable|string|max:200',
    'error_404_button2_icon' => 'nullable|string|max:50',
    'error_404_particles' => 'nullable|string|max:2',
    'error_404_animation' => 'nullable|string|max:20',
    'error_404_code_color' => 'nullable|string|max:20',
    'error_404_code_size' => 'nullable|string|max:10',
];
